// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_N8Wn1xt-k_E6rE1phW8Hbe-7oaTd9b0',
    appId: '1:723105161107:web:6c1887406d0ccadc929266',
    messagingSenderId: '723105161107',
    projectId: 'frameviewer-d74b1',
    authDomain: 'frameviewer-d74b1.firebaseapp.com',
    storageBucket: 'frameviewer-d74b1.appspot.com',
    measurementId: 'G-J3TYG35M5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0gnMeyHIDYDNHas-wqXiGF47Tjo2TVio',
    appId: '1:723105161107:android:44c94a3f40c5ce3f929266',
    messagingSenderId: '723105161107',
    projectId: 'frameviewer-d74b1',
    storageBucket: 'frameviewer-d74b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZVASv4N8YPzMHY3td-OoslRX2_ZDymqA',
    appId: '1:723105161107:ios:83d1db5d6b6e9c33929266',
    messagingSenderId: '723105161107',
    projectId: 'frameviewer-d74b1',
    storageBucket: 'frameviewer-d74b1.appspot.com',
    iosClientId: '723105161107-d86dv98au71kgi31rgc33vn3i8nhg8r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataViewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZVASv4N8YPzMHY3td-OoslRX2_ZDymqA',
    appId: '1:723105161107:ios:83d1db5d6b6e9c33929266',
    messagingSenderId: '723105161107',
    projectId: 'frameviewer-d74b1',
    storageBucket: 'frameviewer-d74b1.appspot.com',
    iosClientId: '723105161107-d86dv98au71kgi31rgc33vn3i8nhg8r1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataViewer',
  );
}
